import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";
import { createPerson, signIn, withDb, capture } from "./support";

test("@core Sensitive and unsupported HR questions require consent before the complete ticket chain, with unrelated-user denial", async ({ page }, info) => {
  const learner = await createPerson("LEARNER"), admin = await createPerson("ADMIN"), outsider = await createPerson("LEARNER");
  await signIn(page, learner); await page.goto("/ask-hr");
  await page.getByRole("textbox", { name: "Ask the HR assistant" }).fill("Can you advise on my medication?");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByText(/I can't help with medical questions/)).toBeVisible();
  await page.getByRole("textbox", { name: "Ask the HR assistant" }).fill("I am being bullied at work and need confidential help.");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByText(/it deserves a person/)).toBeVisible();
  await page.getByRole("button", { name: /Ask the HR team directly/ }).click();
  const dialog = page.getByRole("dialog", { name: "Review what you will share with HR" });
  await expect(dialog.getByLabel("Conversation to share")).toContainText("being bullied");
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  expect(await withDb(async db => (await db.query("SELECT count(*)::int n FROM hr_tickets WHERE user_id=$1", [learner.id])).rows[0].n)).toBe(0);
  await page.getByRole("button", { name: "Talk to a person", exact: true }).click();
  await dialog.getByRole("button", { name: "Share and create ticket", exact: true }).click();
  await page.getByRole("link", { name: "View your ticket", exact: true }).click();
  const ticketUrl = new URL(page.url()).pathname, ticketId = ticketUrl.split("/").at(-1)!;
  await page.getByLabel("Reply to HR").fill("Please contact me after my shift.");
  await page.getByRole("button", { name: "Send reply", exact: true }).click();
  await expect(page.getByText("Your reply was sent to HR.", { exact: true })).toBeVisible();
  await page.context().clearCookies(); await signIn(page, admin); await page.goto(`/admin/tickets/${ticketId}`);
  await expect(page.getByText("Please contact me after my shift.", { exact: true })).toBeVisible();
  await page.getByLabel("Reply to employee").fill("HR will contact you privately after your shift.");
  await Promise.all([page.waitForEvent("load"), page.getByRole("button", { name: "Reply", exact: true }).click()]);
  await Promise.all([page.waitForEvent("load"), page.getByRole("button", { name: "Mark resolved", exact: true }).click()]);
  await page.context().clearCookies(); await signIn(page, learner); await page.goto("/inbox");
  await page.locator(`a[href="${ticketUrl}"]`).first().click();
  await expect(page.getByText("HR will contact you privately after your shift.", { exact: true })).toBeVisible();
  await expect(page.getByText("Resolved — thanks for reaching out.", { exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByText("Resolved — thanks for reaching out.", { exact: true })).toBeVisible();
  await capture(page, info, "resolved-hr-chain");
  await page.context().clearCookies(); await signIn(page, outsider); await page.goto(ticketUrl);
  await expect(page.getByText("HR will contact you privately after your shift.", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: /not found|couldn't find/i })).toBeVisible();
});

test("@core Policy ingestion failure preserves the active version; retry publishes new scoped answers and old citation history", async ({ page }) => {
  // Alphabetic tokens cannot accidentally become PII-redacted phone numbers.
  const admin = await createPerson("ADMIN"), learner = await createPerson("LEARNER"), token = `Policy${randomUUID().replaceAll("-", "").slice(0, 10).replace(/\d/g, digit => "ghijklmnop"[Number(digit)])}`;
  const title = `QA ${token} procedure`;
  const publish = async (body: string) => {
    await page.goto("/admin/corpus?view=publish");
    await page.getByLabel("Title", { exact: true }).fill(title);
    await page.getByLabel("Effective date", { exact: true }).fill("2026-01-01");
    await page.getByLabel("Document (markdown)").fill(body);
    await page.getByRole("button", { name: "Publish & ingest", exact: true }).click();
  };
  await signIn(page, admin);
  await publish(`# ${token}\n\n## Procedure\n${token} employees use the blue checklist before starting.`);
  await expect(page).toHaveURL(/\/admin\/corpus$/);
  const original = await withDb(async db => (await db.query("SELECT id FROM policy_docs WHERE title=$1 AND status='ACTIVE'", [title])).rows[0].id);
  await page.context().clearCookies(); await signIn(page, learner); await page.goto("/ask-hr");
  await page.getByRole("textbox", { name: "Ask the HR assistant" }).fill(token);
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByText(/use the blue checklist/)).toBeVisible();
  const originalCitation = page.locator(`a[href^='/policy/${original}?']`).first();
  await expect(originalCitation).toBeVisible();
  await originalCitation.click(); await expect(page.getByRole("heading", { name: "Procedure", exact: true })).toBeFocused();
  await page.context().clearCookies(); await signIn(page, admin);
  await publish("# Empty policy heading");
  await expect(page.getByRole("main").getByRole("alert")).toBeVisible();
  expect(await withDb(async db => (await db.query("SELECT status FROM policy_docs WHERE id=$1", [original])).rows[0].status)).toBe("ACTIVE");
  expect(await withDb(async db => (await db.query("SELECT count(*)::int n FROM policy_docs WHERE title=$1", [title])).rows[0].n)).toBe(1);
  await page.context().clearCookies(); await signIn(page, learner); await page.goto("/ask-hr");
  const retainedResponse = page.waitForResponse(r => r.url().endsWith("/api/hr") && r.request().method()==="POST");
  await page.getByRole("textbox", { name: "Ask the HR assistant" }).fill(token);
  await page.getByRole("button", { name: "Send", exact: true }).click();
  const retainedEvents = (await (await retainedResponse).text()).split("\n").filter(s=>s.startsWith("data: ")).map(s=>JSON.parse(s.slice(6)));
  const retained = retainedEvents.find(e=>e.type==="final");
  expect(retained.answer).toContain("blue checklist");
  expect(retained.citations.some((c: { docId: string })=>c.docId===original)).toBe(true);
  await page.context().clearCookies(); await signIn(page, admin);
  await publish(`# ${token}\n\n## Procedure\n${token} employees now use the green checklist before starting.`);
  await expect(page).toHaveURL(/\/admin\/corpus$/);
  await page.context().clearCookies(); await signIn(page, learner); await page.goto("/ask-hr");
  const answer = page.waitForResponse(r => r.url().endsWith("/api/hr") && r.request().method()==="POST");
  await page.getByRole("textbox", { name: "Ask the HR assistant" }).fill(token);
  await page.getByRole("button", { name: "Send", exact: true }).click();
  const events = (await (await answer).text()).split("\n").filter(s => s.startsWith("data: ")).map(s=>JSON.parse(s.slice(6)));
  const result = events.find(e=>e.type==="final");
  expect(result.answer).toContain("green checklist"); expect(result.answer).not.toContain("blue checklist");
  expect(result.citations.every((c: { docId: string })=>c.docId!==original)).toBe(true);
  await page.goto(`/policy/${original}?section=${encodeURIComponent(`${token} › Procedure`)}`);
  await expect(page.getByText("Superseded", { exact: true })).toBeVisible();
  await expect(page.getByText(`${token} employees use the blue checklist before starting.`, { exact: true })).toBeVisible();
});

test("@core Completing a selected review keeps the next pending item actionable", async ({ page }) => {
  const admin = await createPerson("ADMIN"), bank = randomUUID(), first = randomUUID(), next = randomUUID();
  await withDb(async db => {
    await db.query("INSERT INTO question_banks(id,name) VALUES($1,'QA queue fallback')", [bank]);
    await db.query("INSERT INTO questions(id,bank_id,type,status,body) VALUES($1,$3,'truefalse','DRAFT',$4),($2,$3,'truefalse','DRAFT',$5)", [first,next,bank,JSON.stringify({prompt:"First fallback review",correct:[0]}),JSON.stringify({prompt:"Next fallback review",correct:[0]})]);
  });
  await signIn(page, admin); await page.goto(`/admin/reviews?view=drafts&item=${first}`);
  await Promise.all([page.waitForEvent("load"),page.getByRole("button",{name:"Approve",exact:true}).click()]);
  await expect(page.getByRole("button",{name:"Approve",exact:true})).toBeVisible();
  await expect(page.getByRole("navigation",{name:"Question drafts",exact:true}).locator('[aria-current="page"]')).toHaveCount(1);
});
