import { createHash, X509Certificate } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

/** Trust only the QA proxy's existing loopback certificate in disposable
 * Chromium profiles. Never use a blanket certificate-error bypass there:
 * repeated DevTools certificate callbacks can exhaust Chromium's retries.
 * This module is imported only by QA tooling, never application code.
 */
export function localChromiumTls(baseURL: string) {
  const url = new URL(baseURL);
  if (!["localhost", "127.0.0.1"].includes(url.hostname) || !["http:", "https:"].includes(url.protocol)) {
    throw new Error("Chromium qualification requires a loopback HTTP(S) URL");
  }
  if (url.protocol === "http:") return { args: [] as string[], ignoreHTTPSErrors: false as const, certificatePath: null, metadata: { origin: url.origin, mode: "Loopback HTTP; certificate checking is not bypassed" } };
  // Fixed to the public certificate generated by scripts/qa-https.mjs. Missing,
  // malformed, expired or non-loopback certificates fail before browser launch.
  const certificatePath = resolve(".artifacts/qa-tls/localhost.crt");
  const certificate = new X509Certificate(readFileSync(certificatePath));
  const validFrom = Date.parse(certificate.validFrom), validTo = Date.parse(certificate.validTo);
  if (!Number.isFinite(validFrom) || !Number.isFinite(validTo) || !certificate.checkHost("localhost") || !certificate.checkIP("127.0.0.1") ||
      Date.now() < validFrom || Date.now() > validTo) {
    throw new Error("QA certificate must be current and identify both loopback hosts");
  }
  const spki = createHash("sha256").update(certificate.publicKey.export({ format: "der", type: "spki" })).digest("base64");
  return {
    args: [`--ignore-certificate-errors-spki-list=${spki}`],
    ignoreHTTPSErrors: false as const,
    certificatePath,
    metadata: { origin: url.origin, mode: "Exact loopback certificate SPKI; all other certificate validation stays strict", spki, certificateFingerprint256: certificate.fingerprint256, validTo: certificate.validTo },
  };
}

export function assertQaNodeTls(tls: ReturnType<typeof localChromiumTls>) {
  if (process.env.NODE_TLS_REJECT_UNAUTHORIZED === "0") throw new Error("QA must not disable Node TLS validation");
  if (tls.certificatePath && resolve(process.env.NODE_EXTRA_CA_CERTS ?? "") !== tls.certificatePath) {
    throw new Error("Use npm run test:e2e so the exact QA certificate is available before Node starts");
  }
}
