import { redirect } from "next/navigation";
import { readSession } from "@/lib/auth/session";
import { acknowledgePrivacyNotice } from "@/lib/auth/login";
import { Button, Card } from "@/components/ui";

export default async function PrivacyNoticePage() {
  const session = await readSession();
  if (!session) redirect("/login");
  return (
    <main className="flex min-h-dvh items-center justify-center px-4 py-8">
      <Card className="animate-enter w-full max-w-xl p-6">
        <h1 className="mb-2 text-xl font-medium">How LuLu Learn uses your data</h1>
        <div className="prose-ll text-sm">
          <p>Before you start, here is what this platform records and why — in plain language.</p>
          <h3>What we collect</h3>
          <ul>
            <li><strong>Training activity</strong> — courses you open, video watch progress, quiz answers and scores, and daily-drill practice. Used for your training record and compliance reporting.</li>
            <li><strong>Assessment integrity events</strong> — during monitored assessments only: when you leave the exam screen or exit fullscreen. No camera and no screen recording in this version. You will always see a consent screen first.</li>
            <li><strong>AI conversations</strong> — questions you ask the lesson Tutor and the HR assistant, so you can revisit them and so HR can improve answers. Identifying details are removed before AI processing.</li>
          </ul>
          <h3>Who processes it</h3>
          <p>AI answers are generated by Anthropic (Claude) and text-matching uses Voyage AI — both US-hosted processors under data-processing agreements. Your name is never sent to them.</p>
          <h3>How long we keep it</h3>
          <p>Chat history and AI logs: up to 12 months. Integrity events: 6 months after an assessment is finalized. Raw watch data: 90 days. Your completion records and certificates are kept as required by employment law.</p>
          <h3>Your rights</h3>
          <p>You can ask HR for a copy of your data or for correction. Only HR — never line managers — can see your HR-assistant conversations, and only when you escalate a question to them.</p>
        </div>
        <form action={acknowledgePrivacyNotice} className="mt-6">
          <Button type="submit" className="w-full">I understand — continue</Button>
        </form>
      </Card>
    </main>
  );
}
